spring:
  profiles:
    active: test
  application:
    name: orion-auth

server:
  port: 8082

knife4j:
  enable: true
  setting:
    swagger-model-name: 数据模型
    enable-version: true
    enable-footer: false

mybatis-plus:
  # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: io.ispacc.orion

# Sa-Token 配置
sa-token:

  # ------- SSO-模式二相关配置
  sso:
    # Ticket有效期 (单位: 秒)，默认五分钟
    ticket-timeout: 300
    # 所有允许的授权回调地址
    allow-url: "*"
